翔实的失败报告
===================================================================================
示例中的测试尝试去创建一个宽度为2的元素，并断言产出的元素的宽度的确为2。如果这个断言失败，**失败报
告** 就会包括 **文件名** 和该断言 **所在的行号**，以及一条 **翔实的错误消息**：
```scala
import org.scalatest.FunSuite
import Element.elem

class ElementSuite extends FunSuite {
  test("elem result should have passed width"){
    val ele = elem('x', 2, 3)
    assert(ele.width == 3)
  }
}
```
失败报告：
```
2 did not equal 3
ScalaTestFailureLocation: ElementSuite at (ElementSuite.scala:7)
Expected :3
Actual   :2

org.scalatest.exceptions.TestFailedException: 2 did not equal 3
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
    ......
```
为了在断言失败时提供描述性的错误消息，**ScalaTest会在编译时分析每次传入assert调用的表达式**。

**ScalaTest的assert方法并不在错误消息中区分实际和预期的结果，它们仅仅是提示我们左侧的操作元跟右侧的
操作元不相等。如果你想要强调实际和预期的差别，可以换用ScalaTest的assertResult方法**，示例：
```scala
import org.scalatest.FunSuite
import Element.elem

class ElementSuite extends FunSuite {
  test("elem result should have passed width"){
    val ele = elem('x', 2, 3)
    assertResult(3){
      ele.width
    }
  }
}
```
失败报告：
```
Expected 3, but got 2
ScalaTestFailureLocation: ElementSuite at (ElementSuite.scala:7)
org.scalatest.exceptions.TestFailedException: Expected 3, but got 2
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
    ......
```

